### ISSUE TITLE
invalid super call

### ISSUE THREAD

**Issue by stefanpenner** [timoxley/ordered-set#1]
likely old compiler, internals appear broken

calling

``` js
OrderedSet = require('ordered-set')
new OrderedSet()
```

```
Users/stefanpenner/src/fast-ordered-set/node_modules/ordered-set/index.js:285
  Set.call(this, items);
      ^
TypeError: Constructor Set requires 'new'
    at OrderedSetCacheOnRead.Set (native)
    at new OrderedSetCacheOnRead (/Users/stefanpenner/src/fast-ordered-set/node_module
s/ordered-set/index.js:285:7)
    at orderedSet (/Users/stefanpenner/src/fast-ordered-set/benchmarks/alloc.js:17:10)
    at Object.<anonymous> (/Users/stefanpenner/src/fast-ordered-set/benchmarks/alloc.j
s:21:8)
    at Module._compile (module.js:426:26)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Function.Module.runMain (module.js:467:10)
    at startup (node.js:117:18)
```

**Comment by stefanpenner** [comment]
i believe natives aren't subclassable yet in v8, which is the source of the issue.

**Comment by timoxley** [comment]
Ahh, yes this is a problem. Dang.
